"""
Django settings for rclone project.
Generated by 'django-admin startproject' using Django 1.8.4.
For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '0%c!5s9h1i&q%8d#bccgpcgx!u=o8u*kqvn-$qrw97g*4wf5ey'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
	'suit',
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'django.contrib.sites',
	'main',
	'accounts',
	'favorites',
	'actstream',
	

	#3rd party apps
	

	'django_forms_bootstrap',
	'guardian',
	'easy_thumbnails',
	'userena',
	'disqus',
	'envelope',
	'honeypot',
	'froala_editor',
	'whoosh',
	'haystack',
	'tastypie',
	'django_select2'

	

)

MIDDLEWARE_CLASSES = (
	'django.contrib.sessions.middleware.SessionMiddleware',

	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'rclone.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [os.path.join (BASE_DIR,'templates')],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'rclone.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.sqlite3',
		'NAME': 'mydatabase',
	}
}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_L10N = True

USE_TZ = True

Date_Format = 'c'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR), "static_in_env", "media_root")
MEDIA_URL = '/media/'


STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), "static_in_env", "static_root")
STATIC_URL = '/static/'
STATICFILES_DIRS = (
	os.path.join(BASE_DIR, "static_in_pro", "our_static"),
  
)



AUTHENTICATION_BACKENDS = (
	'userena.backends.UserenaAuthenticationBackend',
	'guardian.backends.ObjectPermissionBackend',
	'django.contrib.auth.backends.ModelBackend',
)

ANONYMOUS_USER_ID = -1  

AUTH_PROFILE_MODULE = 'accounts.MyProfile'  


USERENA_SIGNIN_REDIRECT_URL = '/'
USERENA_REDIRECT_ON_SIGNOUT  = '/'

LOGIN_URL = '/accounts/signin/'
LOGOUT_URL = '/accounts/signout/'
USERENA_ACTIVATION_REQUIRED = False

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'yourmail'
EMAIL_HOST_PASSWORD = 'yourpassword'

SITE_ID = 1

HONEYPOT_FIELD_NAME = 'email2'

DISQUS_API_KEY = 'MWIe4SAYeXBPqYEQs60rlo4GF85VAt952ITY7zHasQEI0yAe8iTem48b3IkPQd5a'
DISQUS_SECRET_KEY = 'niGpR5Gx0yJiVFOF02RtlfFCda5kOTirGXeJ1boU9EoUITTg1HsYDSTFiv8xZCqg'
DISQUS_WEBSITE_SHORTNAME = 'ebagu'



FROALA_EDITOR_BUTTONS = ('bold', 'italic', 'strikeThrough', 'underline', '|', 'color', 'fontSize', 'paragraphFormat', 'align',
						 'formatOL', 'formatUL',  '|', 'insertImage', 'insertLink', 'quote', 'insertHR', '|', 'undo', 'redo', 'clearFormatting', '|' , 'html', 'fullscreen')
FROALA_EDITOR_OPTIONS = {
	'language': 'ko',
	'heightMin': 500,
	'toolbarButtons': FROALA_EDITOR_BUTTONS
}
FROALA_EDITOR_PLUGINS = ('align', 'char_counter', 'code_view', 'colors', 'file',
		'font_size','image', 'link', 'lists', 'paragraph_format', 'quote', 'table', 'url', 'fullscreen')
FROALA_EDITOR_THEME = 'gray'



WHOOSH_INDEX = os.path.join(BASE_DIR,'whoosh/')


HAYSTACK_CONNECTIONS = {
	'default': {
		'ENGINE': 'haystack.backends.whoosh_backend.WhooshEngine',
		'PATH': WHOOSH_INDEX,
	},
}

from django.utils.translation import ugettext_lazy as _
LANGUAGES = (
	('en', _('English')),
	('ko', _('Korean')),
)

LOCALE_PATHS = (
	os.path.join(BASE_DIR, 'locale'),
)